### PR TITLE
faster recallculate, faster recent unknown morphes, added ability to …

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
I made recalculate faster by using add_notes and add_cards instead of sql query, now it's able to recalculate 40k cards in under 2 minutes. I made already seen be much faster that  anki no longer freezes, the way I fixed it is that it no longer checks every card for unknown morphs only cards that the user has specified to use with morphman, also now it only looks for unknown morphs in cards that have been reviewed recently because if a card has already has non recently been reviewed it can't have recent unknown morphs. Also a list of proper nouns in their profile folder can add names.txt

### CODE REVIEW

**Comment by mortii** [comment]
Omg, amazing. I'll go review it more in-depth soon, but some initial thoughts:

> I made recalculate faster by using add_notes and add_cards instead of sql query, now it's able to recalculate 40k cards in under 2 minutes.

This is very surprising, with the current build it takes me 2 seconds to recalc 40K cards. What hardware are you using? If this is a common problem there are many more optimizations we could make to speed recalc up.

>I made already seen be much faster that anki no longer freezes, the way I fixed it is that it no longer checks every card for unknown morphs only cards that the user has specified to use with morphman, also now it only looks for unknown morphs in cards that have been reviewed recently because if a card has already has non recently been reviewed it can't have recent unknown morphs. 

Awesome, I wasn't  very happy with the freezing when updating seen morphs.

> Also a list of proper nouns in their profile folder can add names.txt

Legend.

**Comment by Vilhelm-Ian** [comment]
I was just going by intution on how long it takes. I wanted to be conservative and because the old version took so long I felt like 2 minutes is very fast. I just did a benchmark(me starting a clock when I press CTRL+M very high tech) . The api version was able to run recalculate in 15 seconds while the sqlite version took 8:18 minutes or 498 seconds. That makes it 33 times faster

**Comment by mortii** [comment]
> The api version was able to run recalculate in 15 seconds while the sqlite version(0.1.3) took 8:18 minutes or 498 seconds. That makes it 33 times faster.


That's crazy... I don't know why It would be faster because I think Anki uses sqlite? I definitely need to look more into this.
Also how long were the freezes when updating seen morphs? If all sqlite operations take a long time then switching to another db system might be warranted.

**Comment by Vilhelm-Ian** [comment]
> Also how long were the freezes when updating seen morphs? I

3-5 seconds

**Comment by mortii** [comment]
> 3-5 seconds, maybe 2 somewher in that range

Ah ok, that isn't as disastrous as the recalc, thankfully.

Are you using pre-commit? The [pre-commit checks](https://github.com/mortii/anki-morphs/actions/runs/6705776010/job/18226938998?pr=24) are complaining.

**Comment by Vilhelm-Ian** [comment]
No. I spent a lot of time trying to get them to shut up

**Comment by mortii** [comment]
> No. I spent a lot of time trying to get them to shut up. 

Yeah, It's a pain, especially if you aren't used to it, but it is definitely worth it. I'll merge this PR into a dev branch and I'll try to fix the pre-commit complains for you.

> The freezes were not as scary as the recall but they happened quite more often. I could avoid recalculatting but starting a deck was not something I could avoid

Any freezes should definitely be fixed--the seen morph freeze was like 0.1 second or something for me so I didn't really consider it a major problem, same with recalc.  But yeah, definitely worth fixing. The goal should be for recalc to take less than 10 secs for all users imo.

**Comment by mortii** [comment]
Fixing the pre-commit errors took me like 30 seconds, so the code was pretty clean, well done!

**Comment by Vilhelm-Ian** [comment]
> > No. I spent a lot of time trying to get them to shut up.
> 
> Yeah, It's a pain, especially if you aren't used to it, but it is definitely worth it. I'll merge this PR into a dev branch and I'll try to fix the pre-commit complains for you.
> 
> > The freezes were not as scary as the recall but they happened quite more often. I could avoid recalculatting but starting a deck was not something I could avoid
> 
> Any freezes should definitely be fixed--the seen morph freeze was like 0.1 second or something for me so I didn't really consider it a major problem, same with recalc. But yeah, definitely worth fixing. The goal should be for recalc to take less than 10 secs for all users imo.

The thing with the freezes is they created a query using all the cards answered that day. I had 300 medical cards. It's no wonder why the freezes stopped when the function only created queries for the couple of new language cards I had.

**Comment by mortii** [comment]
> The thing with the freezes is they created a query using all the cards answered that day. I had 300 medical cards. It's no wonder why the freezes stopped when the function only created queries for the couple of new language cards I had.

Yeah, the query was overly broad for sure. Keeping track of seen morphs was one of the main things that made fixing undos such a pain.

I'm going to make some changes to the code in the 'dev-pr-merge' branch--the changes might not make sense in isolation, but I have some bug-fixes and other improvements in my local 'highlight' branch that will complement the changes.

Next release will probably be out in a day or two!

Thank you so much!

**Comment by mortii** [comment]
@Vilhelm-Ian how is your performance in v0.2.0-alpha?

**Comment by Vilhelm-Ian** [comment]
Everything works as expected

**Pull request merged**
