### PR TITLE
bugfix: avoid deeply nested SQL query which can crash

### PR DESCRIPTION
**Pull request by hans**
## What is the current behavior?

When opening a deck or reviewing a card in a deck which has seen many new cards today, `rebuild_seen_morphs_today_background` causes an SQL crash. This is because this function produces a query with a deeply nested `OR` expression, breaking the SQL parser.

```
Anki 24.06.3 (d678e393)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: macOS-13.6.7-arm64-arm-64bit

Traceback (most recent call last):
  File "aqt.taskman", line 142, in _on_closures_pending
  File "aqt.taskman", line 86, in <lambda>
  File "aqt.taskman", line 106, in wrapped_done
  File "aqt.operations", line 252, in wrapped_done
  File "/Users/jon/Dropbox (Personal)/Anki/addons21/472573498/ankimorphs_db.py", line 707, in _on_failure
    raise error
  File "concurrent.futures.thread", line 58, in run
  File "aqt.operations", line 242, in wrapped_op
  File "/Users/jon/Dropbox (Personal)/Anki/addons21/472573498/ankimorphs_db.py", line 608, in <lambda>
    op=lambda _: AnkiMorphsDB.rebuild_seen_morphs_today_background(),
  File "/Users/jon/Dropbox (Personal)/Anki/addons21/472573498/ankimorphs_db.py", line 636, in rebuild_seen_morphs_today_background
    am_db.con.execute(
sqlite3.OperationalError: Expression tree is too large (maximum depth 1000)
```

## What is the new behavior?

I've updated the query to use an `IN` expression instead, which doesn't break the parser even with large numbers of values.

## What kind of changes does this PR introduce?

N/A

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code successfully passes pre-commit
- N/A I have commented my code, particularly in hard-to-understand areas
- [x] I am willing to help create documentation/guides for the changes made in this PR
- [x] This PR can be rebased onto main without conflicts (create a backup branch before attempting a rebase)
- N/A I have squashed my commits into sensible portions

### CODE REVIEW

**Comment by hans** [comment]
> Did you study 1000+ new cards in one day?

:) No actually -- there were a little over 1000 card IDs in my query but I certainly didn't study all of those. I didn't look into why there where so many. I assumed that set might include cards which were skipped due to no new morphs? Or perhaps there is another bug behind this..?

**Comment by mortii** [comment]
> I assumed that set might include cards which were skipped due to no new morphs?

Aha, that does make more sense. The `OR is:buried tag:am-known-manually` might be the culprit:

https://github.com/mortii/anki-morphs/blob/59197cb4d2bae6fbe3712352066a8dd38661694a/ankimorphs/ankimorphs_db.py#L651-L652 

https://github.com/mortii/anki-morphs/blob/59197cb4d2bae6fbe3712352066a8dd38661694a/ankimorphs/ankimorphs_db.py#L665-L668

Did you have a particularly productive session where you studied and used the 'K' key to go through 1k cards, or are the same cards being skipped at the start of every session?

**Comment by hans** [comment]
I didn't manually bury but I'm assuming that's what AnkiMorphs did under the hood?
I had just added a lot of morphs to a known morphs file, and while using a pretty new deck it was frequently skipping over hundreds of cards with known morphs.

**Comment by mortii** [comment]
> I didn't manually bury but I'm assuming that's what AnkiMorphs did under the hood?

Yes, skipped cards are buried, but they aren't given any tags though, so they shouldn't match the query.

Could you do me a favor and copy paste your add-on json configs? Found at: Tools -> Add-ons -> select "AnkiMorphs" -> click on the "Config" button on the right sidebar.

**Pull request merged**
