### PR TITLE
fixed learn now

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
also I suggest we add this function to recalc "mw.col.sched.reposition_new_cards(selected_cards, 0, 1, False, True)" instead of changing the due date of every card. The above functions takes True as an argument which tells it to readjust all the other cards

### CODE REVIEW

**Comment by Vilhelm-Ian** [comment]
> Wow, that looks like such a clean fix. I've been hesitant to use reposition because it updates the due of all the cards in the new-queue, but it is definitely a more robust approach.

I didn't want to mention

**Comment by mortii** [comment]
I did some quick testing and it does seem to work. Thank you so much!

**Comment by Vilhelm-Ian** [comment]
> Wow, that looks like such a clean fix. I've been hesitant to use reposition because it updates the due of all the cards in the new-queue, but it is definitely a more robust approach.

An issue I had since recently but didn't want to mention is after pressing recalc and sync a lot of cards need to be resynced. My hunch that the issue is manually setting the due date of a lot of cards.

**Comment by mortii** [comment]
> @mortii An issue I had since recently but didn't want to mention is after pressing recalc and sync a lot of cards need to be resynced. My hunch that the issue is manually setting the due date of a lot of cards.

Aha, that does seem to be a problem, I just assumed that they were synced because they were rightfully updated. The old (and slow) approach of using mw.col.db.executemany() to update the cards actually had a bug that made sync not work, so by now using mw.col.update_cards() sync actually works. 

We probably need to have an if-statement before setting any card properties in recalc to solve this issue...

**Comment by Vilhelm-Ian** [comment]
can you try with "mw.col.sched.reposition_new_cards" Because when I reposition a card from the anki browser and adjust other cards it dosen't lead to long sync

**Comment by mortii** [comment]
> can you try with "mw.col.sched.reposition_new_cards" Because when I reposition a card from the anki browser and adjust other cards it dosen't lead to long sync

very interesting, maybe that means its updating the notes that are causing the problem? I'll experiment and try to fix it.

**Pull request merged**
