### PR TITLE
Ability to use custom frequency lists

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
## What is the current behavior?
It dosen't allow for custom frequency lists to be used

Please link any related issues.

## What is the new behavior?
It allows for custom frequency lists to be used

## What kind of changes does this PR introduce?
It adds an option to the settings dialog for a user to import a custom frequency list

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)
- [ maybe] This change requires a documentation update

## Checklist:

- [ ] My code successfully passes pre-commit. No but I think everything important passed
- [ ] I have commented my code, particularly in hard-to-understand areas. Yes
- [ ] I am willing to help create documentation/guides for the changes made in this PR. Yes
- [ ] This PR can be rebased onto main without conflicts (create a backup branch before attempting a rebase). Yes

### CODE REVIEW

**Comment by Vilhelm-Ian** [comment]
Ignore this merge. There is problem

**Comment by Vilhelm-Ian** [comment]
Okay I realized what the problem was. I wanted a card with a morph that is not in frequency.csv to have a difficulty something like 1_000_000 but it currently it's being capped at 50k. @mortii can I add an exception to the algorithm where cards with morphs not in the frequency list are heavily peanilized

**Comment by Vilhelm-Ian** [comment]
I just got an idea how to approach this from a different point of view. Instead of penalizing a card for having a morph not in the frequency list. To mark that morph as unknown. This would be way better for my usecase. But I don't know if it would be better for most people. The main reason why I have so many words outside the frequency list in my collection is that spacy still hasn't been implemented. So maybe when spacy is implemented the penalizing approach would prove better. Now that I typing this I realize maybe both can be combined to mark as a morph as unknown and penalize the card.

@mortii since you are studying japanese and they have a lemmazation of words. Can you test out my pull request with the subtitles of an anime you are watching. Do you find that that AnkiMorphs suggest you more words out of the show.

**Comment by Vilhelm-Ian** [comment]
I actually got it working 🎊. And I am loving the ability to [deep dive](https://www.youtube.com/watch?v=ey2nsLTH1jM&t=1589s) again

**Comment by mortii** [comment]
Awesome!

Could you squash all your commits into one? makes the git history cleaner.

**Comment by Vilhelm-Ian** [comment]
I will try

**Comment by Vilhelm-Ian** [comment]
@mortii done. Lazygit is an awesome tool

**Comment by mortii** [comment]
@Vilhelm-Ian I could not recommend [GitKraken](https://www.gitkraken.com/) enough, It makes everything a million times easier.

Btw, I updated the [setup guide](https://mortii.github.io/anki-morphs/developer_guide/setup.html#linux) a while back with some more info on pre-commit, does it make sense or is there something that could be added to make it better?

**Comment by Vilhelm-Ian** [comment]
the last time I tried to follow tthat I did pipi install anki --break-system-packages .

And anki top bar was missing. And spent a lot of time trying to figure out where I went wrong. Untill I read that requirements.txt contais anki. 

```
× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

**Comment by mortii** [comment]
That's the advantage of using a virtual environment, it does not mess with your global packages.

What happens if you just copy paste the entire thing in terminal and press enter?
```
python3.9 -m pip install --upgrade pip
python3.9 -m pip install virtualenv
python3.9 -m virtualenv venv
source venv/bin/activate
python3.9 -m pip install -r requirements.txt
pre-commit install
```

**Comment by Vilhelm-Ian** [comment]
I get the same error plus
```
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
created virtual environment CPython3.11.5.final.0-64 in 105ms
  creator CPython3Posix(dest=/home/jovan/programiranje/forks/anki-morphs/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jovan/.local/share/virtualenv)
    added seed packages: pip==23.3.1, setuptools==68.2.2, wheel==0.41.3
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
venv/bin/activate (line 48): Unsupported use of '='. In fish, please use 'set VIRTUAL_ENV '/home/jovan/programiranje/forks/anki-morphs/venv''.
VIRTUAL_ENV='/home/jovan/programiranje/forks/anki-morphs/venv'
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file venv/bin/activate
source: Error while reading file 'venv/bin/activate'
error: externally-managed-environment
```

**Comment by mortii** [comment]
what operating system are you using?

**Comment by Vilhelm-Ian** [comment]
Linux Manjaro. It's no issue I just had to type bash to run the command

**Comment by mortii** [comment]
Ah, nice! I haven't heard of fish before.

Are you able to follow the rest of the setup docs or is it terrible? I want to make the on-boarding for people as smooth as possible.

**Comment by Vilhelm-Ian** [comment]
yup the rest of the guide is clear

**Comment by mortii** [comment]
Excellent! Are you able to make pre-commit run successfully? right now it fails on black, which just formats the files automatically, so you should just re-commit its changes for it to go away.

**Comment by Vilhelm-Ian** [comment]
i can't get it to download python3.9 I tierd pip install python3.9 but it can't find the package.

this is how the venv looks

```(venv) [jovan@jovan-20rr bin]$ ls
activate          blackd        isort-identify-imports  pip3           py.test     stubtest        wheel-3.11
activate.csh      distro        jsonschema              pip-3.11       pytest      symilar         wheel3.11
activate.fish     dmypy         markdown_py             pip3.11        python      undill
activate.nu       flask         mypy                    pre-commit     python3     venv
activate.ps1      get_gprof     mypyc                   pylint         python3.11  virtualenv
activate_this.py  get_objgraph  nodeenv                 pylint-config  pyuic6      waitress-serve
anki              identify-cli  normalizer              pylupdate6     send2trash  wheel
black             isort         pip                     pyreverse      stubgen     wheel3
```

when I try to commit I get this

```
git commit -m "hi"
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/jovan/programiranje/forks/anki-morphs/venv/bin/python', '-mvirtualenv', '/home/jovan/.cache/pre-commit/repozn9akgr4/py_env-python3.9', '-p', 'python3.9')
return code: 1
```

**Comment by mortii** [comment]
What happens if run 
```
python3.9 --version
```
in the terminal?

**Comment by Vilhelm-Ian** [comment]
python3.9: command not found

**Comment by mortii** [comment]
The fact that anki uses python 3.9 and not a newer version that can be automatically downloaded by most package managers makes me irrationally angry. I originally used python 3.11, and when I ran anki from my virtual environment everything would work fine, but when I ran it from outside the dev environment where anki used 3.9 then stuff would break because the python code was too new...

I used this method do download 3.9: https://askubuntu.com/questions/1318846/how-do-i-install-python-3-9/1318849#1318849

Hopefully its not super hard to do something equivalent in Manjaro? I haven't used Arch in years, so I'm not a great help when it comes to that stuff.

**Comment by Vilhelm-Ian** [comment]
i am going to try tomorrow

**Comment by Vilhelm-Ian** [comment]
@mortii I got it to pass all checks. I used ``pyenv`` can you add it to the documentation that they should use pyenv to install python 3.9 .  You can't just tell them how to install pyenv because the steps are different for different os and shell.

**Comment by mortii** [comment]
@Vilhelm-Ian Amazing! This functionality is a huge milestone for the project, truly well done! :clap: 

I think I'll move the combobox from the 'recalc' tab to the individual note filters to make it more granular, after that I'll push a new release.

I'll absolutely update the setup guide, installing 3.9 is definitely a non-trivial step.

Thank you so much!

**Comment by mortii** [comment]
[setup docs](https://mortii.github.io/anki-morphs/developer_guide/setup.html) are now updated.

**Comment by mortii** [comment]
@Vilhelm-Ian I pushed the #59 changes to main. Could you test if it works for you? I just want to double check before I create a new release. You might have to delete meta.json.

**Comment by Vilhelm-Ian** [comment]
@mortii I tried it out everything works as expected. It's awesome that you can use per note type frequency lists. Was it hard to implement?

**Comment by mortii** [comment]
@Vilhelm-Ian Glad it works! It was surprisingly easy, you took care of the most difficult parts :clap:

**Comment by mortii** [comment]
@Vilhelm-Ian btw do you have a good german frequency csv file you would be willing to share? I want to have a section in the docs where people can download pre-made frequency files.

**Pull request merged**
