### PR TITLE
Added ability to select a word during reviewing and add it to the names file

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
image

### CODE REVIEW

**Comment by mortii** [comment]
That is absolutely genius, I have never thought about doing something like that. This webview approach could also be used for morph stuff, like searching other cards for that specific morph, etc. That is so good, wow.

We should probably make it slightly more robust, like splitting on whitespace (eg. someone selected first name and surname at the same time), and trimming extra whitespaces etc. I could take care of that if you don't want to do it.

**Comment by mortii** [comment]
I just thought of another related thing: 
I added a error pop-up dialog if "names.txt" does not exist but the user selected the option, but that is unnecessarily complicated, we could just create the file if it does not already exist, less hassle for the user.

**Comment by Vilhelm-Ian** [comment]
I agree

**Comment by mortii** [comment]
I'll merge after I fix re-sync

**Comment by mortii** [comment]
> We should probably make it slightly more robust, like splitting on whitespace (eg. someone selected first name and surname at the same time), and trimming extra whitespaces etc. I could take care of that if you don't want to do it.

> I added a error pop-up dialog if "names.txt" does not exist but the user selected the option, but that is unnecessarily complicated, we could just create the file if it does not already exist, less hassle for the user.

I did these things, and I also moved the code to a separate 'name_file_utils.py' file.

Thank you!

**Pull request merged**
