### PR TITLE
Added option to recalc on sync

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
image

### CODE REVIEW

**Comment by mortii** [comment]
Absolutely amazing, I've wanted this feature forever.

I'll make some tiny adjustments like not running on anki startup, and then I'll push out a release!

**Comment by mortii** [comment]
I don't know why the pre-commit-ci bot is making commits on pull-requests... I'll get rid of it.

You may or may not make your life easier if you "force pull" main and from then on only work on dev branches, it might make your git less tangled.

**Comment by Vilhelm-Ian** [comment]
Meaning on doing that

**Comment by Vilhelm-Ian** [comment]
@mortii do you need help with something else

**Comment by mortii** [comment]
> @mortii do you need help with something else

I'm working on updating the guide/docs, and it's my least favorite thing to do, so any help is very welcomed!

I've added [a guide entry for for the names.txt option](https://mortii.github.io/anki-morphs/user_guide/setup/names.html), maybe you could help write it?

**Pull request merged**
