### PR TITLE
Add more statistics in readability analyser

### PR DESCRIPTION
**Pull request by Jcuhfehl**
## What is the current behavior?
Currently, the readability analyser only displays statistics about morph instances. This PR also adds stats for the individual morphs, and aggregate stats for all files analyzed.

Fixes most of what I requested in #160 

[//]: # (Set items to checked like this: [x])

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code successfully passes pre-commit
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I am willing to help create documentation/guides for the changes made in this PR
- [x] This PR can be rebased onto main without conflicts (create a backup branch before attempting a rebase)
- [x] I have squashed my commits into sensible portions

### CODE REVIEW

**Comment by mortii** [comment]
Awesome, thanks!

My initial impressions:
1. The "total" row is very cool
2. Seeing the instances is actually a huge improvement
3. I'm a little concerned about the width of the columns. Do you think it would be okay to remove "instances" from the last three column headers? It would make it more consistent with the previous columns. Either that or the previous columns should have "Known Morphs", etc., which I think would be very wide and wordy.

**Comment by Jcuhfehl** [comment]
What could replace "instances"? Calling them known morphs and such does seem very wordy, but I also can't really think of a way to replace instances without losing information.

What should I do with the lint errors? I'll try to get black working for the formatting at least, but some of the lints seem hard to fix to me (like too many arguments and too many locals). Also using `|` for overloading types in a function argument is valid python, what should I do with that?

**Comment by mortii** [comment]
> What could replace "instances"? Calling them known morphs and such does seem very wordy, but I also can't really think of a way to replace instances without losing information.

Yeah, it's tricky. I was thinking we could completely drop the word in the last three columns and it would just be inferred from the "Total Instances" column before them, just like how it's inferred from the "Total Morphs" column. But idk if that is actually a great idea... do you have any strong feelings about it?

> What should I do with the lint errors? I'll try to get black working for the formatting at least, but some of the lints seem hard to fix to me (like too many arguments and too many locals). Also using | for overloading types in a function argument is valid python, what should I do with that?

The pipe type annotation was added in python 3.10, and the standard Anki build uses 3.9, so the addon actually crashes with your current code. You can either switch to `Union[typ1, typ2]` or you could just use `from __future__ import annotations`. I hate using `Union`, so I plan on switching to the future import so I can uses pipes instead. 

That being said, I could fix all the minor linting problems for you --it's a lot easier for someone that has pre-commit up and running locally.

**Comment by Jcuhfehl** [comment]
I think the way it is right now is the least bad option, but I don't really have any strong feelings.

It would be great if you could fix the lint problems. I didn't realize anki uses an outdated python version by default (obligatory i use arch btw)

**Comment by mortii** [comment]
Mhm, disambiguating the columns might require being more verbose. That being said, my intuition strongly suggests that there should be a somewhat better approach. Wordy column headers can ironically obfuscates the overall picture of the data since you have to do more reading (which in turn makes me zone out and lose interest).

Basically, what we are trying to achieve is having this data displayed:
```
Unique Morphs
Unique Known
Unique Learning
Unique Unknown

Total Morphs
Total Known
Total Learning
Total Unknown
```

One approach could be to split the table in two (by adding an empty column?) and with that we could extract the common elements (`Unique` and `Total`) and explicitly show that this group contains unique and the other group contains total. That could turn out to be hideous and confusing and fail completely, but I want to experiment a little bit to at least rule it out.

I'll come back to this tomorrow when I'm (hopefully) less sleep deprived.

**Comment by mortii** [comment]
Another alternative could be to add a line break in each header, something like this:
```
Unique   Unique    ...   Total     Total   ...
Morphs   Known           Morphs    Known
```

that would take care of the width problem at least

**Comment by Jcuhfehl** [comment]
screenshot_2024-03-10T09:50:00
I think this is probably the best solution indeed

**Pull request merged**
