### PR TITLE
bury when marked as name

### PR DESCRIPTION
**Pull request by Vilhelm-Ian**
It's just a one line commit

### CODE REVIEW

**Comment by mortii** [comment]
This does not update 'seen morphs' right?
If that is the case then you might get the same problem on the next card that is shown.

**Comment by mortii** [comment]
tracking seen morphs is painful

**Comment by Vilhelm-Ian** [comment]
You are right that you might have the same issue on the next card. But I think it's a nice middle ground. Between solving it completely and not doing anything. If somebody faces multiple times the name he can just recalculate

**Comment by mortii** [comment]
Hmm, I have some ideas on how to develop this further,. I'll do it on top of this.

**Comment by Vilhelm-Ian** [comment]
@mortii I got an idea I am just telling you because I am not good with sql could we just do known_morphs.push({id:card.id, base: name, lemma: name})

**Pull request merged**
